const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
const ADD_TODO_FAILED = "ADD_TODO_FAILED";

const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
const REMOVE_TODO_FAILED = "REMOVE_TODO_FAILED";

const COMPLETE_TODO_REQUEST = "COMPLETE_TODO_REQUEST";
const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
const COMPLETE_TODO_FAILED = "COMPLETE_TODO_FAILED";

const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";

const GET_ALL_TODOS_REQUEST = "GET_ALL_TODOS_REQUEST";
const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_SUCCESS";
const GET_ALL_TODOS_FAILED = "GET_ALL_TODOS_FAILED";

export default {
  ADD_TODO_REQUEST,
  ADD_TODO_SUCCESS,
  ADD_TODO_FAILED,
  REMOVE_TODO_REQUEST,
  REMOVE_TODO_SUCCESS,
  REMOVE_TODO_FAILED,
  COMPLETE_TODO_REQUEST,
  COMPLETE_TODO_SUCCESS,
  COMPLETE_TODO_FAILED,
  EDIT_TODO_REQUEST,
  EDIT_TODO_SUCCESS,
  EDIT_TODO_FAILED,
  GET_ALL_TODOS_REQUEST,
  GET_ALL_TODOS_SUCCESS,
  GET_ALL_TODOS_FAILED
};
