export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';


export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';



export const COMPLETE_REQUEST = 'COMPLETE_REQUEST';
export const COMPLETE_SUCCESS = 'COMPLETE_SUCESS';
export const COMPLETE_FAILED = 'COMPLETE_FAILED';



export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_SUCCESS = 'EDIT_SUCESS';
export const EDIT_FAILED = 'EDIT_FAILED';



export const GET_ALL_TODOS_REQUEST = 'GET_ALL_TODOS_REQUEST';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCESS';
export const GET_ALL_TODOS_FAILED = 'GET_ALL_TODOS_FAILED';